const host = "http://localhost:5000";
export const registerRoute = `${host}/api/auth/register`;
export const loginRoute = `${host}/api/auth/login`;
export const sendMessageRoute = `${host}/api/messages/addMsg`;
export const getContactsRoute = `${host}/api/auth/getContacts`;
export const getAllUsersRoute = `${host}/api/auth/getAllUsers`;
export const sendRequestRoute = `${host}/api/auth/sendRequest`;
export const getRequestsRoute = `${host}/api/auth/getRequests`;
export const acceptRequestRoute = `${host}/api/auth/acceptRequest`;
